version: '3.0'
networks:
  default:
    driver: bridge
  external:
    name: rnet
    external: true
services:
  mapserver:
    image: jjrom/mapserver:latest
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - default
      - external
    ports:
      - ${MAPSERVER_EXPOSED_PORT:-8282}:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s
    volumes:
      - ${MAPSERVER_MAP_DIRECTORY:-./map}:/map
      - ${MAPSERVER_DATA_DIRECTORY:-./data}:/data
      - ./mapserver.conf:/etc/mapserver.conf
