version: '2.1'
networks:
  default:
    driver: bridge
  external:
    external:
      name: rnet
services:
  mapserver:
    image: jjrom/mapserver:1.0
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - default
      - rnet
    ports:
      - ${MAPSERVER_EXPOSED_PORT:-8282}:80
    env_file: 
      - ${ENV_FILE:-config.env}
    #environment: 
      ### Server configuration (uncomment to change values) 
      #- NGINX_FASTCGI_BUFFERS=8 16k
      #- NGINX_FASTCGI_BUFFER_SIZE=32k
      #- NGINX_FASTCGI_BUSY_BUFFERS_SIZE=32k
      #- NGINX_FASTCGI_CONNECT_TIMEOUT=60s
      #- NGINX_FASTCGI_SEND_TIMEOUT=60s
      #- NGINX_FASTCGI_READ_TIMEOUT=60s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s
    volumes:
      - ${MAPSERVER_MAP_DIRECTORY:-./map}:/map
